version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rails_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

  web:
    build:
      context: /home/iris1/iris-systems-recruitment-task-2025-Jishnu-Prasad888
    depends_on:
      db:
        condition: service_started
    deploy:
      replicas: 3
    environment:
      DATABASE_URL: postgres://user:password@db:5432/rails_db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    depends_on:
      web:
        condition: service_started
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - /home/iris1/iris-systems-recruitment-task-2025-Jishnu-Prasad888/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
