version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/rails_db"
    networks:
      - app-network
    deploy:
      replicas: 3  # <-- This scales the web containers to 3 instances

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
